web/flaskr/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    db.init_app(app)

    return app

web/flaskr/main/__init__.py
from flask import Blueprint
from flask_restful import Api

main = Blueprint('main', __name__)

from .views import index, area_ana
from .views.plot.test_plot_view import test_plot_view
from .views.plot import plot_distribution_view

restful = Api(main)

from flaskr.main.api.locate.AProvider import AProvider

restful.add_resource(AProvider, '/api/locate/a')

from flaskr.main.api.locate.BProvider import BProvider

restful.add_resource(BProvider, '/api/locate/b')

web/flaskr/main/api/__init__.py
def resp(data, msg="success", code=200):
    return {"data": data, "msg": msg, "code": code}

web/flaskr/main/views/area_ana.py
from flask import render_template, make_response, request
from .. import main


@main.route('/area_ana', methods=['GET'])
def area_ana():
    locate_a = request.args.get("locate_a", "全部")
    locate_b = request.args.get("locate_b", "全部")
    # print("/area_ana get locate_a:{locate_a} locate_b:{locate_b}".format(locate_a=locate_a, locate_b=locate_b))
    return make_response(render_template('area_ana.html', locate_a=locate_a, locate_b=locate_b))

web/flaskr/main/views/index.py
from flask import render_template, make_response
from .. import main


@main.route('/', methods=['GET', 'POST'])
def index():
    return make_response(render_template('index.html'))

web/flaskr/main/views/plot/__init__.py
from io import BytesIO
import base64
from flask import make_response, render_template
import seaborn.apionly as snsa

# 解决matplotlib字体不显示的问题
from pylab import *

mpl.rcParams['font.sans-serif'] = ['SimHei']  # 指定默认字体
mpl.rcParams['axes.unicode_minus'] = False  # 解决保存图像是负号'-'显示为方块的问题


def reload_view():
    import importlib
    importlib.reload(mpl)
    importlib.reload(plt)
    importlib.reload(snsa)


def gen_view_data(fig):
    sio = BytesIO()
    fig.savefig(sio, format='png')
    data = base64.encodebytes(sio.getvalue()).decode()
    return data


def make_view_response(fig):
    '''
    生成可视化图片相应
    :param data:
    :return:
    '''
    data = gen_view_data(fig)
    return make_response(render_template('plot/base.html', data=data))

web/flaskr/templates/area_ana.html
{% extends "base.html" %}
{% block page_content %}

<script type="text/javascript" src="{{ url_for('static', filename='js/plot/area_ana.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/page_area_ana.js') }}"></script>

<input id="ip_locate_a" type="hidden" value="{{locate_a}}"/>
<input id="ip_locate_b" type="hidden" value="{{locate_b}}"/>

{% if error %}
<p class=error><strong>Error:</strong> {{ error }}{% endif %}

<div class="row">
    <label>一级区域</label>
    <div class="btn-group">
        <button id="bt-locate-a" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
            全部 <span class="caret"></span>
        </button>
        <ul id="ul-locate-a" class="dropdown-menu">
        </ul>
    </div>


    <label>二级区域</label>
    <div class="btn-group">
        <button id="bt-locate-b" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
            全部 <span class="caret"></span>
        </button>
        <ul id="ul-locate-b" class="dropdown-menu">
        </ul>
    </div>
</div>

<div class="row" style="margin-top: 10px">

    <div class="panel panel-default">
        <div class="panel-heading">面积分布（单位：㎡）</div>
        <div class="panel-body">
            <div id="plot_area_distribution">
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">总价分布（单位：万元）</div>
        <div class="panel-body">
            <div id="plot_price_distribution">
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">每平米价格分布（单位：元）</div>
        <div class="panel-body">
            <div id="plot_unit_price_distribution">
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">建造时间分布（单位：年）</div>
        <div class="panel-body">
            <div id="plot_build_time_distribution">
            </div>
        </div>
    </div>

</div>

{% endblock %}

web/flaskr/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}房价分析{% endblock %}

{% block head %}
{{ super() }}

<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/main.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}">
<script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% endblock %}

{% block body %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">房价分析</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="nav-index"><a href="{{ url_for('main.index') }}">首页</a></li>
                <li id="nav-area_ana"><a href="{{ url_for('main.area_ana') }}">区域分析</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li id="nav-setting"><a href="#">设置</a></li>
            </ul>
        </div>
    </div>
</div>


{% block content %}
<div class="container">
    {% for category,message in get_flashed_messages(with_categories=true) %}
    <div id="flash" class="alert alert-{{category}}" role="alert">
        <button type="button" class="close" data-dismiss="alert" onclick="$('#flash').hide()">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

web/flaskr/templates/index.html
{% extends "base.html" %}
{% block page_content %}

  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
{% endblock %}

web/flaskr/templates/plot/base.html
<div>
    {% if error %}<h4>{{error}}</h4>{%endif%}
    {% if data %}
    <img src="data:image/png;base64,{{data}}"/>
    {% endif %}
</div>